# src/config/config.yaml

data:
  raw_dir: "../../data/raw"
  final_dir: "../../data/final"
  visuals_dir: "../../data/visuals"

preprocessing:
  rolling_window_sizes:
    '15m': [[3, '45m'], [12, '3h'], [48, '12h']]
    '1h': [[4, '4h'], [24, '1d'], [168, '1w']]
    '4h': [[2, '8h'], [6, '1d'], [42, '1w']]
    '1d': [[7, '1w'], [30, '1m'], [365, '1y']]
  correlation_threshold: 0.95
  scaler_type: 'standard'  # options: 'standard', 'minmax'

imbalance_handling:
  oversample_strategy:
    3: 2000
    2: 2000
    -3: 2000
    -2: 2000
  undersample_strategy:
    1: 2000
    0: 2000
    -1: 2000

training:
  sequence_length: 30
  batch_size: 64
  total_timesteps: 200000
  save_freq: 50000
