# File: config/base_config.yaml

defaults:
  - _self_
  - exchange: exchange_config
  - features: features_config
  - model: model_config
  - trading: trading_config
  - logging: logging_config
  - ray: ray_config

data:
  start_date: "2023-01-01"
  end_date: "2023-12-31"

agents:
  num_agents: 5

training:
  num_episodes: 1000

evaluation:
  num_episodes: 100

paths:
  model_save_path: "./models/saved/"
