exchange:
  name: mexc
  symbol: BTC/USDT
  timeframe: 1h
  trading_pairs:
    - BTC/USDT
    - ETH/USDT
  rate_limit: 1200

data:
  start_date: "2023-01-01"
  end_date: "2023-12-31"

features:
  target_column: close
  feature_selection:
    method: "SelectFromModel"
    threshold: 0.01
    max_features: 10

model:
  type: LSTM
  params:
    input_size: 10
    hidden_size: 64
    num_layers: 2
    output_size: 3

agent:
  type: DQN
  params:
    learning_rate: 0.001
    gamma: 0.99
    epsilon_start: 1.0
    epsilon_end: 0.01
    epsilon_decay: 0.995

training:
  batch_size: 32
  num_episodes: 1000
  test_size: 0.2
  random_state: 42

evaluation:
  num_episodes: 100

trading:
  initial_balance: 10000
  transaction_fee_percent: 0.001

logging:
  level: INFO
  file: logs/trading_bot.log

paths:
  model_save_path: models/