# config/exchange_config.yaml
exchange:
  name: mexc
  api_key: ${env:MEXC_API_KEY}
  api_secret: ${env:MEXC_API_SECRET}
  trading_pairs:
    - BTC/USDT
    - ETH/USDT
  timeframe: 1m # Default timeframe
  rate_limit: 1200
