# config/exchange_config.yaml
exchange:
  name: binance
  api_key: "${env:BINANCE_API_KEY}" # Load from environment variable
  api_secret: "${env:BINANCE_API_SECRET}" # Load from environment variable
  trading_pairs:
    - BTC/USDT
    - ETH/USDT
  timeframe: 1m # Default timeframe
  rate_limit: 1200