# config/trading_config.yaml

trading:
  initial_balance: 10000.0  # Starting balance in USD
  max_trade_size: 0.1  # Maximum 10% of balance per trade
  risk_per_trade: 0.02  # 2% risk per trade
  transaction_fee: 0.001  # 0.1% fee per trade
  slippage: 0.0005  # 0.05% slippage
  leverage: 1  # No leverage by default
  stop_loss: 0.05  # 5% stop loss
  take_profit: 0.10  # 10% take profit
  trade_history_limit: 1000  # Number of past trades to keep
